### ISSUE TITLE
Possible to support PHP 5.2?

### ISSUE THREAD

**Issue by ericguo** [fontis/fontis_recaptcha#2]
Can't install the extension because of PHP version.

CONNECT ERROR: Package community/Fontis_Recaptcha 2.5.0: requires PHP version >= 5.3.0 and <= 6.0.0 current is: 5.2.15

**Comment by chnorton** [comment]
We honestly just don't test any of our work on PHP 5.2 as it's no longer maintained. I'd suggest it makes more sense to move to hosting that has a current version of PHP as 5.2 doesn't even get security patches now.

**Comment by ericguo** [comment]
OK. It's time to upgrade the PHP. Thanks
